export const MockResult = {
    personalities: [
        { personality: 'Empathetic', percentage: 15 },
        { personality: 'Patient', percentage: 10 },
        { personality: 'Aggressive', percentage: 5 },
        { personality: 'Manipulative', percentage: 8 },
        { personality: 'OpenMinded', percentage: 12 },
        { personality: 'Reliable', percentage: 6 },
        { personality: 'Supportive', percentage: 10 },
        { personality: 'Confident', percentage: 5 },
        { personality: 'Loyal', percentage: 8 },
        { personality: 'Constructive', percentage: 9 },
        { personality: 'Respectful', percentage: 7 },
        { personality: 'Needy', percentage: 3 },
        { personality: 'Stubborn', percentage: 4 },
        { personality: 'Selfish', percentage: 2 },
        { personality: 'Insecure', percentage: 2 },
        { personality: 'Insensitive', percentage: 1 },
        { personality: 'Impatient', percentage: 3 },
        { personality: 'Impulsive', percentage: 1 },
        { personality: 'Egotistical', percentage: 0 },
        { personality: 'Honest', percentage: 2 },
        { personality: 'Generous1234', percentage: 1 },
    ],
    evaluationDescriptions:
        "This individual's communication suggests a mix of personality traits, notably demonstrating open-mindedness, empathy, and supportiveness, but also signs of manipulation and aggression in certain messages.",
};
