export const EvaluationFormat = {
    personalities: [
        { personality: 'Empathetic', score: 0 },
        { personality: 'Patient', score: 0 },
        { personality: 'Aggressive', score: 0 },
        { personality: 'Manipulative', score: 0 },
        { personality: 'OpenMinded', score: 0 },
        { personality: 'Reliable', score: 0 },
        { personality: 'Supportive', score: 0 },
        { personality: 'Confident', score: 0 },
        { personality: 'Loyal', score: 0 },
        { personality: 'Constructive', score: 0 },
        { personality: 'Respectful', score: 0 },
        { personality: 'Needy', score: 0 },
        { personality: 'Stubborn', score: 0 },
        { personality: 'Selfish', score: 0 },
        { personality: 'Insecure', score: 0 },
        { personality: 'Insensitive', score: 0 },
        { personality: 'Impatient', score: 0 },
        { personality: 'Impulsive', score: 0 },
        { personality: 'Egotistical', score: 0 },
        { personality: 'Honest', score: 0 },
    ],
    evaluationDescriptions: 'Example summary of the evaluation less than 50 words',
};
